#Valores aproximados baseados em: IPCC, International Energy Agency e National Renewable Energy Laboratory (Pedi para o Gemini me ajudar com estes dados)
fatoresCO2 = {
    "Potencial hidráulico": 24,
    "Gás de Alto Forno - CM": 1100,
    "Óleo Diesel": 778,
    "Bagaço de Cana de Açúcar": 18,
    "Gás Natural": 490,
    "Urânio": 12,
    "Licor Negro": 35,
    "Óleo Combustível": 840,
    "Calor de Processo - CM": 1000,
    "Outros Energéticos de Petróleo": 850,
    "Resíduos Florestais": 30,
    "Calor de Processo - GN": 490,
    "Carvão Mineral": 1001,
    "Gás de Refinaria": 650,
    "Biogás - RU": 230,
    "Cinética do vento": 11,
    "Lenha": 30,
    "Casca de Arroz": 25,
    "Radiação solar": 45,
    "Carvão Vegetal": 28,
    "Gás de Alto Forno - PE": 1100,
    "Gás de Alto Forno - Biomassa": 150,
    "Calor de Processo - OF": 840,
    "Biogás - RA": 180,
    "Capim Elefante": 20,
    "Óleos vegetais": 50,
    "Biogás-AGR": 150,
    "Resíduos Sólidos Urbanos - RU": 400,
    "Etanol": 38,
    "Carvão - RU": 600,
    "Biogás - Floresta": 120
}